task_id: "a_plus_b"
time_limit: 1.0
memory_limit: 32
checker: "lcmp"
grouper: "min"
groups:
  - full_score: 50
    tests: 5
  - full_score: 50
    tests: 5
compile_files:
  - cpp:
    - "grader.cpp"
    - "grader.h"
  - python:
    - "test.py"